worldcoin/orb-firmware

- bootloader/boards/diamond_main.conf
- bootloader/prj.conf
sector count increased as we now use the external flash for the secondary partition.
Not the case on Pearl so this commit fixes this.
> dfu: sector count changes only on diamond

- lib/dfu/dfu.c
- lib/dfu/include/dfu.h
- main_board/app/include/app_config.h
- main_board/app/src/optics/ir_camera_system/ir_camera_system.c
- main_board/app/src/optics/ir_camera_system/ir_camera_system_tests.c
- main_board/app/src/system/dfu/dfu_tests.c
A large page-sized buffer is needed to compute crc for external flash.
Stack allocation is preferred over static allocation to make this RAM chunk be usable by other runner-called functions.
> dfu: stack-allocated buffer increases runner stack size

- .gitignore
- utils/env/.envrc.example
- utils/env/flake.lock
- utils/env/flake.nix
I use flakes to manage developer shells, so I figured I'd add a simple flake for setting up pyocd, protobuf, etc.
> tools: added nix flake for convenience

- main_board/src/power/boot/boot.c
- main_board/src/system/version/version.c
- main_board/src/temperature/fan/fan.c
- west.yml
Add support for Mainboard hardware version 4.2 which is used in the Diamond B3 build.
fixes O-2619
> version: add Mainboard B3

- main_board/CMakeLists.txt
when setting ORB=pearl or ORB=diamond, the board
is selected automatically.
it allows to use one profile per Orb on CLion:
the profile selects the board when loading the CMakeLists.txt. We still have to create a new profile for Debug/Release
> build: new variable make board selection easier

- boards/arm/diamond_main/diamond_main.dts
- main_board/src/optics/ir_camera_system/ir_camera_system_hw.c
Add support for different signals on Front Unit 6.2 which is used in the Diamond B3 build. On Front Unit 6.2 the electronic fuse circuit was removed and replaced by a simple power switch.
fixes O-2607
> front unit: support different signals on B3

- boards/arm/diamond_main/diamond_main.dts
- main_board/src/power/boot/boot.c
Initializes the reset signal of the USB hub and puts it on an inactive level during boot to enable the USB hub.
> boot: enable usb hub

- main_board/src/power/battery/battery_amber.c
- main_board/src/pubsub/pubsub.c
- west.yml
Read State-of-Health register from Amber battery and send its value to Jetson.
fixes O-2426
> battery: add reading of SoH register

- boards/arm/diamond_main/diamond_main.dts
- drivers/led_strip/Kconfig.spi_rgb_led
- main_board/src/ui/rgb_leds/front_leds/front_leds.c
will ditch support for Diamond PoC2
fixes O-2608
> diamond: front-leds: build 3 to have 136 RGB LEDs (72 ring, 64 shroud)

- boards/arm/diamond_main/diamond_main.dts
- main_board/src/system/version/version.c
- main_board/src/system/version/version.h
- west.yml
uses io expander on the boards
fixes O-2189
> versions: diamond: read power board & front unit versions

- main_board/src/power/battery/battery_amber.c
- main_board/src/power/battery/battery_ruby.c
- main_board/src/pubsub/pubsub.c
- west.yml
when battery detected as removed
with `orb-mcu-util`:
```
Shutdown(ShutdownScheduled { shutdown_reason: BatteryRemoved, ms_until_shutdown: Some(7000) })
```
fixes O-2693
> battery: send shutdown scheduled

- main_board/src/optics/1d_tof/tof_1d.c
- main_board/src/optics/1d_tof/tof_1d.h
- main_board/src/optics/optics.c
in case ir-leds are turned on, but not actuated,
use a callback to turn them off on safety
critical conditions.
fixes O-2587
> ir-leds: 1d-tof callback to stop ir-leds

- main_board/src/ui/rgb_leds/front_leds/front_leds.c
- west.yml
not all LEDs were actuated due to a bug in the zephyr driver. 
see [zephyr](https://github.com/worldcoin/zephyr/tree/fouge/apa-leds-fix)
fixes O-2678
> rgb-leds: fix apa102 

- main_board/src/runner/runner.c
- west.yml
use SyncDiagData to monitor Orb's connection state.
Because SyncDiagData is only used when the Orb is connected, not receiving this message means the Orb is not connected.
> memfault: connectivity metrics

- lib/health_monitoring/heartbeat.c
- main_board/config/memfault_reboot_reason_user_config.def
so that these reboots are not tracked as "unspecified"
> memfault: track reboot reason on heartbeat timeout

- main_board/src/optics/mirror/mirror.c
- main_board/src/optics/mirror/mirror.h
- axis: The background is assembly and supply chain driven: we need to make sure that an assembly worker cannot plug in the steppers the wrong way around. Connectors are located on the main board so that the cables are too short if connected incorrectly.
- direction: motor behavior changed with new motors on diamond. issue is still undocumented due to lack of datasheet from the manufacturer, but use this as a workaround for now.
fixes O-2723
> mirror: diamond: invert motors and direction

- utils/cmake/version.cmake
reported to memfault, easier to find commit based on displayed version: no need to convert from decimal to hex
> version: use hex format for commit sha

- utils/cmake/version.cmake
fix image creation when BUILD_FROM_CI not used
> versions: initialize build number to 0 for local builds

- boards/arm/diamond_main/diamond_main.dts
same as data phase.
will increase ISO-TP communication speed by ~8.
fixes O-2725
> can-fd: diamond: increase arbitration datarate to 1Mbps

- lib/dfu/dfu.c
- main_board/src/optics/ir_camera_system/ir_camera_system_hw.c
- main_board/src/power/boot/boot.c
- main_board/src/pubsub/pubsub.c
- main_board/src/pubsub/pubsub_tests.c
isolate in the compilation unit to prevent
any mistake with incorrect cross-referencing
> semaphores: declare them as `static`

- lib/can_messaging/canbus_tx_isotp.c
to ensure we don't leave stale data into the struct
> iso-tp: reset context struct between each tx

- main_board/src/ui/rgb_leds/front_leds/front_leds.c
on pearl, strip didn't update if any of the
center or ring didn't change when marking
the led buffer as dirty.
> rgb-leds: fix refresh of rgb led

- main_board/src/ui/rgb_leds/front_leds/front_leds.c
- main_board/src/ui/rgb_leds/rgb_leds.c
ensure that modifications to
the LED buffer are guarded
behind a mutex.
We don't wait for the mutex to
be available in
`set_*_leds_sequence` because
these are used with a refresh rate
so we simply wait for the next
rgb-leds values to be sent.
fixes O-2709
> rgb-leds: fix flicker

- main_board/src/ui/rgb_leds/front_leds/front_leds.c
- main_board/src/ui/rgb_leds/rgb_leds.c
don't assert to log error on mutex locked
because it's going to happen and it's fine.
> rgb-leds: remove error on mutex locked

- main_board/src/temperature/fan/fan_tests.c
- main_board/src/temperature/sensors/temperature.c
- make sure the measured fan speed decreases with 2 fan speeds
- unit test for over-temperature callback and behavior in nominal, over temperature and critical temperature conditions
fixes O-2749
> tests: over-temperature and fan 

- main_board/src/optics/ir_camera_system/ir_camera_system.h
- main_board/src/optics/ir_camera_system/ir_camera_system_tests.c
test that ir leds are turned off
after 6 seconds (timeout in tests)
```
START - test_ir_led_timeout
[00:01:29.455,000] <wrn> ir_camera_system: Turning off IR LEDs after 6s of inactivity
PASS - test_ir_led_timeout in 6.108 seconds
```
fixes O-2750
> tests: ir-led timeout

- main_board/src/temperature/fan/fan_tests.c
- main_board/src/voltage_measurement/voltage_measurement_tests.c
to bring back HIL tests from CI
new fan test had some issues on Pearl
increased 12V range (in case battery is low)
> tests: hil tests

- lib/uart_messaging/uart_messaging.c
SOFT_ASSERT includes a software breakpoint and
the uart communication happens over DMA
making it very hard to debug on errors, which happen most of the time when stopped at a breakpoint in
another location.
> debug: remove usage of SOFT_ASSERT in uart_message.c

- main_board/src/ui/rgb_leds/cone_leds/cone_leds.c
- main_board/src/ui/rgb_leds/front_leds/front_leds.c
- main_board/src/ui/rgb_leds/operator_leds/operator_leds.c
- main_board/src/ui/rgb_leds/rgb_leds.h
- west.yml
When supported by the hardware, the RGB LEDs can be dimmed using a specific byte sent to the LED. The byte is a value between 0 and 31, where 0 is the minimum brightness and 31 is the maximum. So far, we defaulted the value to 31.
See https://github.com/worldcoin/orb-control-api-client/pull/164
> rgb-leds: control the dimming value of the RGB LEDs

- main_board/src/optics/mirror/mirror.c
On a cold POR/boot of the Orb; going from a disconnected or discharged 
battery to connected/charged, it takes time for the power rails to come up
and stabilize for the LM25117 buck controller and subsequently the 
TMC5041 stepper motor driver to be able to act on SPI commands
TODO ** TUNE DOWN DELAYS AFTER TALKING TO HARDWARE TEAM **
> mirror: add a delay for the auto-homing procedure

- .github/workflows/format.yml
- main_board/src/ui/rgb_leds/front_leds/front_leds_tests.c
enforce usage of formatters & linters configured with the pre-commit config file
> ci: add pre-commit checks

- main_board/src/power/boot/boot.c
- main_board/src/temperature/fan/fan.h
fan can get stuck at 100% otherwise in the
bootloader, and if an update is performed,
stays at full speed for a few dozens seconds
fixes O-2913
> fan: turn off before rebooting

- lib/can_messaging/Kconfig
- lib/can_messaging/canbus_tx_isotp.c
decreases RAM usage
ISO-TP is mostly used with request/response
pattern (max 1 ack + 1 data for each received request);
broadcast messages are sent over CAN-FD.
A maximum of 8 rx contexts are allowed
(never actually reached), so 16 tx messages
should suffice.
> fix(can): decrease ISO-TP TX queue size

- lib/can_messaging/Kconfig
- lib/can_messaging/can_messaging.c
- lib/can_messaging/canbus_tx.c
- lib/can_messaging/canbus_tx_isotp.c
with the introduction of a new thread, the CAN state is polled regularly to ensure that the device will always seek recovery. The callback feature used in the past doesn't seem to be reliable.
fixes ORBP-185
> fix(can): CAN device to always seek recovery

- utils/env/entrypoint.sh
- utils/env/environment.yml
- utils/test/requirements.txt
python 3.13 for zephyr 4 (requires at least python 3.10)
fix entrypoint.sh file used by clion. reset PATH before sourcing env files & conda env
> chore(env): update python and dependencies

- utils/docker/Dockerfile
update base os version from ubuntu 22.04 to 24.04
update protoc version to 27.0
update sdk version to 0.17.0
updated github variables to pull docker image `ghcr.io/worldcoin/orb-firmware-build:20`
> chore(env): update Dockerfile

- main_board/CMakeLists.txt
- main_board/src/optics/ir_camera_system/unit_tests/ir_camera_system/CMakeLists.txt
- utils/math/generate_half_sine.py
use `${PYTHON_EXECUTABLE}` to ensure the Python executable loaded by CMake/west is used
and shebang for python script `#!/usr/bin/env python3`
> chore(zephyr): proper python3 calls

- boards/arm/diamond_main/diamond_main.dts
- main_board/include/app_config.h
`-` is generally more used in device tree properties
cleaner comments about gpio expanders pca9535
remove unused macro
> refactor(dts+app_config): better comments and clean unused

- utils/docker/Dockerfile
git lfs is used to pull the repo, can be useful inside the container.
> fix(docker): add missing g++ & git-lfs

- .github/workflows/fast-forward.yml
Trying to pass GITHUB_SECRET directly to the fast forward pipeline, as this value is taken from env variables in sequoia-pgp/fast-forward@v1 action
Signed-off-by: [Michał Leszczyński] [michal.leszczynski@toolsforhumanity.com](mailto:michal.leszczynski@toolsforhumanity.com)
> chore(env): Update fast forward pipeline token

- .github/workflows/docker_build.yml
docker is mainly used in ci
makefile is used locally, for dev purposes
> fix(ci): do not build new docker image on Makefile change

- main_board/src/system/tracing_user.c
__BKPT leads to hard fault when it's hit without a debugger attached.
> fix(tracing): do not call __BKPT() if not debugging

- main_board/src/ui/rgb_leds/front_leds/front_leds.c
do not check for null color too early, otherwise the pattern that don't get a color as a parameters cannot be applied.
> fix(rgb-leds): fix front leds patterns that cannot be applied

- lib/dfu/dfu.c
free cpu usage with windows of 10ms every 200ms when computing crc32 over secondary slot image, executed in the runner thread. this allows at least the watchdog to be fed.
> feat(dfu): prevent thread starvation when computing crc32

- main_board/src/system/dfu/dfu_tests.c
instead of reimplementing the crc computation check, measure the time it takes to compute CRC over entire secondary slot and ensure it takes less time that 1500ms on Diamond (orb-mcu-util ack timeout, orb-update-agent being 2500ms).
the test has been run locally on Diamond B3.
and [run on Pearl](https://github.com/worldcoin/priv-orb-firmware/actions/runs/12692029069/job/35376424221?pr=558)
fixes ORBP-590
> feat(dfu_tests): unit test dfu_secondary_check()

- main_board/src/optics/1d_tof/tof_1d.c
don't silently fail if an error occurs when setting a sensor attribute when initializing vl53l1x
> fix(1d-tof): report error setting sensor attribute

- main_board/src/optics/1d_tof/tof_1d.c
we omitted a few mutex locks when calling the sensor API, which made access to other peripherals on the i2c
bus fail.
> fix(1d-tof): properly use mutex when using vl53l1x

- lib/include/mcu_message_wrapper.h
- main_board/src/pubsub/pubsub.h
because we want to minimize memory used to store messages to send, we compute the number of bytes taken to wrap the payload to send into an McuMessage.
The number of bytes is guessed thanks to the McuMessage max size and all
the payloads max sizes which are all known at compile time.
In case the biggest payload among the 4 available changes, the computation needs to change: we now use the max of all 4 so that we don't have to throw an error in case the biggest payload changes.
> fix(pubsub): compute McuMessage wrapper size without throwing error

- main_board/config/memfault_reboot_reason_user_config.def
- main_board/src/runner/runner.c
- west.yml
https://github.com/worldcoin/orb-messages/pull/42 needs to go in first, then dependency in `west.yml` will be updated in a follow-up commit
publish ShutdownScheduled msg w/JETSON_REQUESTED_REBOOT on mcu-util reboot
fixes ORBP-363
> feat(reboot reason): reason published on mcu-util requested reboot

- drivers/mux_gpio/spi_mux_gpio.c
before trying to use it
in our case, the GPIO port is a GPIO expander so it must be ready.
> chore(spi_mux_gpio): ensure that GPIO is set and ready

- main_board/src/temperature/sensors/temperature.c
and use const when possible in calculate_die_temperature
> refactor(die-temp): improve fetching of calibration values & addresses

- main_board/src/voltage_measurement/voltage_measurement.c
- main_board/src/voltage_measurement/voltage_measurement.h
`inline` not needed (global static)
`else` branch not needed as previous branch returns, so make it clearer.
> refactor(voltage_measurement): remove redundant code

- lib/dfu/dfu.c
- lib/dfu/include/dfu.h
- lib/include/utils.h
- main_board/src/main.c
- main_board/src/system/dfu/dfu_tests.c
- main_board/src/system/dfu/dfu_tests.h
When loading dfu data, if the block_count was larger than what the partition can accept, the processing thread would exit with an error without resetting its internal `dfu_state`, and thus the `wr_idx`. This allowed to write after the buffer boundaries.
Internal state is now reset, and wr_idx and data size always checked before writing the buffer.
Unit tests have been added to validate DFU logic, including valid and edge case scenarios for sequencing, buffer integrity, and semaphore handling.
fixes SEC-1325
> fix(dfu): buffer overflow

- main_board/src/main.c
- main_board/src/optics/ir_camera_system/ir_camera_system.c
- main_board/src/optics/ir_camera_system/ir_camera_system.h
in ir_camera_system.c, so that it doesn't bloat main.c
> refactor(ir-camera): move test reset function

- main_board/log_levels.Kconfig
- main_board/src/system/diag.c
diag_sync must not return is diag data didn't change since last sync, because memfault data is being queued.
> feat(diag): fix synchronization

- boards/tfh/diamond_main/diamond_main.dts
pin usage have changed
from (EN, A0, A1) = (P15, P16, P17) to (EN, A0, A1) = (P17, P15, P16)
fixes ORBP-644
> feat(gpio-exp): diamond: swap a few pins

- boards/tfh/diamond_main/diamond_main.dts
on diamond evt, the operator board has one single LED (was 5) and is connected to a new gpio expander located on the power board.
fixes ORBP-235
> feat(operator-board): diamond: new gpio expander, 1 led

- main_board/src/pubsub/pubsub_tests.c
- main_board/src/temperature/fan/fan_tests.c
- main_board/src/voltage_measurement/voltage_measurement_tests.c
12v not present on diamond evt board
re-enable fan tach test
als is removed until further notice
fixes ORBP-660
> fix(ztests): unit tests for diamond evt

- main_board/src/power/boot/boot.c
init priority wasn't correctly used
> fix(sys_init): ensure i2c1 initialised after power supplies

- main_board/src/optics/mirror/mirror.c
new gimbal with broader range means that we need to increase the number of steps to go to the center.
> feat(gimbal): diamond: new settings for autohoming

- main_board/src/optics/mirror/mirror.c
there are two ways to control the mirror:
- absolute positioning: an angle is set to the mirror, based on initial angle after mirror homing (initial being 45º and 90º)
- relative positioning: apply a delta angle based on current position.
The range is not checked anymore when doing relative positioning to allow for more flexibility during bring-up and testing of diamond evt.
> feat(mirror): remove mirror range check with relative positioning

- main_board/src/optics/ir_camera_system/ir_camera_system.c
- main_board/src/optics/ir_camera_system/ir_camera_system.h
- main_board/src/optics/ir_camera_system/unit_tests/ir_camera_system/template_main.c
- main_board/src/optics/optics.c
- main_board/src/optics/optics.h
- check IR safety circuitry state (pvcc enabled) on setting new FPS, IR LED, wavelength
- allow reset of fps and ir-led to zero in any condition
> feat(ir-camera): conditions to enable/disable ir leds & capture

- lib/can_messaging/Kconfig
- lib/can_messaging/canbus_rx_isotp.c
allow custom configuration of the iso-tp block size (BS) parameter with Kconfig.
> feat(isotp): set iso-tp block size with Kconfig

- main_board/CMakeLists.txt
- main_board/src/optics/ir_camera_system/ir_camera_system.c
- main_board/src/optics/optics.c
disable until we synchronize 1d-tof with rgb frame capture
> chore(1d-tof): diamond: disable to avoid ir light leakage into rgb

- main_board/src/optics/1d_tof/tof_1d.c
- main_board/src/optics/ir_camera_system/ir_camera_system.c
- main_board/src/optics/ir_camera_system/ir_camera_system_tests.c
- main_board/src/optics/optics.c
- main_board/src/optics/optics.h
mutex for i2c is used by 1d-tof, als and temperature module, but not gpio expander pins themselves.
it is needed though for pvcc-enabled which can be checked quite regularly. For the others, because they are only checked during boot (front-unit hardware version), we
can probably leave them unprotected.
> fix(i2c1): use mutex to protect i2c1 bus usage

- lib/storage/storage.c
- main_board/src/pubsub/pubsub.c
when reading (storage peek + storage free), if the area is in a bad state, there was no mechanism to reset the area and thus the thread ended up in a while loop trying to read an unreadable record without being able to free that record.
> fix(storage): reset bad storage area during flush

- main_board/src/main.c
- main_board/src/power/boot/boot.c
sometimes sd card isn't recognized on _cold_ boot: no battery plugged in for a long time, then with a battery freshly inserted and instant boot, we can easily reproduce the issue.
the difference between cold boot, and a fresh reboot is mainly into the voltage at the (super) capacitors.
The need for current when starting to charge the super-caps might alter the voltage at the sd card and/or other components that are not correctly initialized.
The super-caps are thus enabled later in the boot process (after UEFI boots, which needs ~15 seconds).
With this new boot sequence, the sd card seems to be always correctly detected.
> fix(boot): fix sd card boot

- lib/errors/app_assert.c
- lib/errors/include/app_assert.h
ASSERT_SOFT_WITH_MSG allows to pass an additional message to bring even more context.
> feat(error): optional message with assert

- boards/tfh/diamond_main/diamond_main.dts
- main_board/log_levels.Kconfig
- main_board/src/optics/1d_tof/tof_1d.c
- main_board/src/optics/1d_tof/tof_1d.h
- main_board/src/optics/optics.c
1d-tof is behind a multiplexer on dvt board
with deferred init to ensure the correct device is initialized.
fixes ORBP-688
> feat(1d-tof): dvt support

- main_board/src/optics/1d_tof/tof_1d.c
- main_board/src/optics/optics.c
even when safety feature is disabled, report 1d tof distances
don't return early on 1d-tof initialization error
> feat(1d-tof): measure distance at all time

- main_board/src/ui/white_leds/white_leds.c
white leds set with duty cycle in thousandths (0-1000) so ensure the value doesn't exceed 1000.
> chore(white_leds): ensure value doesn't exceed 1000

- lib/include/orb_logs.h
- main_board/src/temperature/sensors/temperature.c
don't pipe all logs to memfault only
also log errors and warning to serial
decrease log level for temperature errors to warning
> fix(logs): errors on serial for service/dev

- lib/health_monitoring/Kconfig
- lib/health_monitoring/orb_state.c
- main_board/src/system/diag.c
do it with sys init, post kernel
so that it's performed before user code
priority defaults to 50
> fix(orb-state): initialize dynamic data

- boards/tfh/diamond_main/diamond_main.dts
- boards/tfh/pearl_main/pearl_main.dts
- main_board/src/ui/sound/sound.c
to get the amplifier device with i2c address, so that all the devices connected to i2c are defined in the device tree, which is easier to find
> refactor(sound): use device tree

- main_board/src/power/battery/battery_amber.c
- main_board/src/power/battery/battery_ruby.c
report an orb state for the power supply (battery or corded)
report corded power supply as "is charging"
increased switch between batteries to 4 seconds
as long as voltage goes back to normal, the corded power supply can be
recognized at runtime
fixes ORBS-1050
> feat(battery): recognize corded power supply & keep state

- lib/watchdog/watchdog.c
the static assertion was checking the kconfig value, that could be overridden.
Better to check overridden
> fix(watchdog): check overridden value that is actually used

- lib/errors/app_assert.c
- lib/health_monitoring/heartbeat.c
- main_board/config/memfault_reboot_reason_user_config.def
- main_board/src/main.c
- main_board/src/optics/mirror/mirror_private.c
- main_board/src/power/boot/boot.c
- main_board/src/ui/rgb_leds/front_leds/front_leds.c
use memfault to log hard assertion failures
decrease usage of it, prefer ASSERT_SOFT or logging errors hard assert might end up being reset with a watchdog and so incorrectly logged.
added reboot reason HardAssert
> chore(assert): improve ASSERT_HARD usage
