- lib/dfu/dfu.c
can happen on brand new device
> dfu: don't fail when secondary slot is empty

- CONTRIBUTING.md
Change paths from "/orb" to "/orb/public".
> documentation: fix paths

- main_board/src/optics/optics.c
- main_board/src/pubsub/pubsub_tests.c
- main_board/src/temperature/fan/fan.c
- main_board/src/temperature/fan/fan_tests.c
- main_board/src/ui/rgb_leds/front_leds/front_leds_tests.c
- main_board/src/voltage_measurement/voltage_measurement_tests.c
some tests are bypassed but tasks added to linear to fix later on.
fixes O-2676
> diamond: b3: fix twister tests

- utils/env/environment.yml
- update protobuf based on conda-forge
- fix paths
> env: fix setup

- west.yml
private events from security mcu
> orb-messages: updated, new events for diamond b3

- main_board/src/main.c
- main_board/src/pubsub/pubsub_tests.c
fix tests running on main_board
> tests: fix

- .github/workflows/twister_native.yml
- .github/workflows/zephyr_build.yml
use --narrow --fetch-opt=--depth=1
> ci: west update to fetch the minimum

- lib/health_monitoring/CMakeLists.txt
- lib/health_monitoring/heartbeat.c
- lib/health_monitoring/heartbeat_test.c
- lib/health_monitoring/include/heartbeat.h
- main_board/src/main.c
> heartbeat: use semaphore instead of k_wakeup()

- boards/arm/diamond_main/diamond_main.dts
- boards/arm/pearl_main/pearl_main.dts
- main_board/README.md
- main_board/debug_uart_dts.overlay
to be enabled by adding an overlay when
compiling the debug target
> logs: disable logs over uart by default

- main_board/src/system/version/version.c
Set hardware version for Diamond B3
> version: memfault to report correct hw version

- main_board/src/ui/rgb_leds/front_leds/front_leds.c
field included into union, my mistake
> rgb-leds: diamond: fix dirty field

- lib/errors/orb_fatal.c
some explanation about Memfault handling
> fatal: memfault: kernel panics as HardFault

- west.yml
> iso-tp: fixed driver in zephyr

- main_board/src/ui/rgb_leds/operator_leds/operator_leds.c
On Pearl, the left LED is the most significant bit
On Diamond, the right LED is the most significant bit
> operator leds: diamond: invert order

- boards/arm/diamond_main/diamond_main.dts
- main_board/src/temperature/sensors/temperature.c
- west.yml
to trigger over temperature mechanism
fix front_unit_tmp_sensor_940_center_top -> front_unit_tmp_sensor_850_center_top
fix front_unit_tmp_sensor_940_center_bot -> front_unit_tmp_sensor_850_center_bot
fixes O-2739
>  temperatures: diamond: average front unit sensors

- main_board/src/main.c
- main_board/src/optics/1d_tof/tof_1d.c
- main_board/src/optics/1d_tof/tof_1d.h
- main_board/src/optics/optics.c
- main_board/src/optics/optics.h
- main_board/src/temperature/sensors/temperature.c
> 1d-tof: fix concurrent i2c bus access

- lib/can_messaging/canbus_tx.c
- lib/dfu/dfu.c
- main_board/src/optics/optics.c
so that these are not uploaded to memfault
> logs: remove useless messages

- main_board/src/optics/ir_camera_system/ir_camera_system_hw.c
> tests: semaphore was set to static variable

- main_board/src/ui/button/button.c
remove disabling of fan on button long-press, on pearl.
> button: pearl: remove disabling of fan on button

- main_board/src/voltage_measurement/voltage_measurement.c
keep track of the value in the logs when
out of range.
> voltage-measurement: better logs

- main_board/README.md
Fix broken link, update directories.
> readme: update main_board readme after open sourcing Orb firmware

- lib/watchdog/watchdog.c
ensure that callback can be set only once and on success
> watchdog: set callback on successful init only

- .github/workflows/compliance.yml
> ci(pr-title): use same pull request events as orb-software

- bootloader/src/main.c
- lib/can_messaging/can_messaging.c
- lib/can_messaging/canbus_rx.c
- lib/can_messaging/canbus_rx_isotp.c
- lib/can_messaging/canbus_tx.c
- lib/can_messaging/canbus_tx_isotp.c
- lib/dfu/dfu.c
- lib/health_monitoring/heartbeat.c
- lib/uart_messaging/uart_messaging.c
- lib/watchdog/watchdog.c
- main_board/src/gnss/gnss.c
- main_board/src/optics/1d_tof/tof_1d.c
- main_board/src/optics/ir_camera_system/ir_camera_system_hw.c
- main_board/src/optics/liquid_lens/liquid_lens.c
- main_board/src/optics/mirror/mirror.c
- main_board/src/power/battery/battery_amber.c
- main_board/src/power/battery/battery_ruby.c
- main_board/src/power/boot/boot.c
- main_board/src/pubsub/pubsub.c
- main_board/src/runner/runner.c
- main_board/src/temperature/fan/fan_tach.c
- main_board/src/temperature/sensors/temperature.c
- main_board/src/ui/ambient_light/als.c
- main_board/src/ui/button/button.c
- main_board/src/ui/rgb_leds/cone_leds/cone_leds.c
- main_board/src/ui/rgb_leds/front_leds/front_leds.c
- main_board/src/ui/rgb_leds/operator_leds/operator_leds.c
- main_board/src/ui/white_leds/white_leds.c
- main_board/src/voltage_measurement/voltage_measurement.c
thread function with explicit cast to `(k_thread_entry_t)`
> chore(zephyr): k_thread_create explicit cast

- utils/docker/Dockerfile
> fix(ci): missing gnupg

- main_board/src/optics/liquid_lens/liquid_lens.c
- ensure that target current to apply is clamped [-400;400]
- ensure that feedback loop takes into account the new current by checking that the PWM value changes and stabilizes after a few dozens milliseconds. This also checks that the ADC conversion works
fixes ORBP-583
> test(liquid_lens): add test to control lens

- bootloader/CMakeLists.txt
to quickly grasp which version is being built
visually appealing
> feat(cmake): emoji to show the kind of build for bootloader

- west.yml
Update dependency for orb-messages for CBOR tamper payload
> chore(cbor_tamper): CBOR tamper payload dependency

- main_board/src/system/version/version.c
- main_board/src/temperature/fan/fan.c
- west.yml
> feat(versions): diamond: new board versions

- boards/tfh/diamond_main/diamond_main.dts
- main_board/src/temperature/sensors/temperature.c
front_unit_tmp_sensor_850_730_right_bot (tmp112@4a) has been removed
fixes ORBP-610
> feat(temperature): remove temperature sensor

- boards/tfh/diamond_main/diamond_main.dts
from 136 on diamond b3 to 118 on evt
> chore(rgb-leds): diamond: decrease front led count

- utils/docker/.dockerignore
* Ensure .git and .gitignore are properly ignored
* Prevent sensitive files from being included in Docker builds
> SEC-1406: Add/update .dockerignore

- boards/tfh/diamond_main/diamond_main.dts
- main_board/src/main.c
- main_board/src/optics/ir_camera_system/ir_camera_system_hw.c
- main_board/src/optics/liquid_lens/liquid_lens.c
- main_board/src/power/boot/boot.c
- main_board/src/system/version/version.c
- main_board/src/system/version/version.h
- main_board/src/temperature/fan/fan.c
- main_board/src/ui/ambient_light/als.c
- main_board/src/ui/ambient_light/als.h
- main_board/src/voltage_measurement/voltage_measurement_tests.c
- west.yml
add reset board versions tracking
don't init als on specific front unit versions (not assembled) function to get version changed to get all boards versions
> feat(versions): versions for all boards

- main_board/src/temperature/fan/fan.c
test now support orb_mcu_Hardware_OrbVersion_HW_VERSION_DIAMOND_EVT
> fix(fan): test: add version compatibility

- .github/workflows/main.yml
- .github/workflows/twister_native.yml
Change token name for public orb repos
> Build: Change token name

- main_board/src/power/boot/boot.c
- main_board/src/system/version/version.c
- main_board/src/temperature/fan/fan.c
- west.yml
only version checks because of minor modifications to these boards
> feat(versions): support main board v4.4 and power board v1.4

- boards/tfh/diamond_main/diamond_main.dts
- main_board/src/ui/white_leds/white_leds.c
period of with maximum timer value over 16-bits to increase resolution, given that the white leds can be very bright.
> feat(white-leds): increase pwm resolution

- main_board/src/optics/ir_camera_system/ir_camera_system_hw.c
- main_board/src/optics/optics.c
use return code to better understand any issue that could occur.
> fix(errors): better handling of errors

- main_board/src/ui/sound/sound.c
so that we don't blow the speaker
> feat(sound): diamond: increase attenuation to -10dB

- main_board/src/optics/mirror/mirror.c
increasing angle must go towards the orb camera
> fix(mirror): fix direction

- boards/tfh/diamond_main/diamond_main.dts
- boards/tfh/pearl_main/pearl_main.dts
- main_board/prj.conf
- west.yml
we've tracking a commit on main since we bumped from zephyr 3 to zephyr 4. This commit tracks the actual release Zephyr 4.1.0, plus a few commits for custom features we want into zephyr, see the worldcoin/zephyr repo.
> feat(zephyr): update to stable v4.1.0

- main_board/src/optics/mirror/mirror_tests.c
new functions to call for mirror homing
> fix(mirror): test: fix tests

- lib/storage/storage.c
- lib/storage/storage_tests.c
- main_board/tests.conf
helps understand the performed tests
> test(storage): more logs during storage test

- main_board/src/system/version/version.c
wasn't set for diamond evt boards
> fix(memfault): fix hardware version string

- main_board/src/runner/runner.c
memfault_metrics_connectivity_connected_state_change cannot be called from isr, so set connectivity into work queue
> fix(connectivity): call memfault connectivity outside interrupt

- main_board/release.conf
CONFIG_STACK_CANARIES -> CONFIG_STACK_CANARIES_ALL
> fix(stack-canaries): config changed in zephyr 4.1

- main_board/release.conf
> chore(stack): reduce randomization of stack pointer

- lib/health_monitoring/heartbeat_test.c
> fix(tests): heartbeat stack size is a kconfig

- lib/dfu/dfu.c
- lib/dfu/include/dfu.h
- main_board/src/runner/runner.c
computing crc over secondary partition in external flash can take a lot of time, and the runner thread should not be taken for a few hundreds milliseconds
> feat(dfu): offload crc32 computation to dfu thread

- lib/dfu/dfu.c
sem_dfu_free_space is taken when checking crc but never freed.
> fix(dfu): free semaphore

- utils/ota/combine_hex_files
universal bash script to combine hex files
> feat(combine_hex_files): add support for macos

- west.yml
> feat(time): message definitions for setting time

- boards/tfh/diamond_main/diamond_main.dts
- main_board/src/temperature/sensors/temperature.c
- west.yml
refactor temperature sensors
fixes ORBP-640
> feat(temperature): diamond: moved sensors

- west.yml
> feat(plug-and-trust): update

- main_board/src/temperature/sensors/temperature.c
die temp & front unit leds to 80ºC
> chore(temperature): increase operating temperatures on diamond

- lib/health_monitoring/include/heartbeat.h
> chore(heartbeat): increase priority

- main_board/src/power/boot/boot.c
> fix(boot): power cycle supply

- main_board/src/main.c
- main_board/src/optics/polarizer_wheel/polarizer_wheel.c
- main_board/src/optics/polarizer_wheel/polarizer_wheel.h
> feat(polarizer): keep track of state

- main_board/src/power/boot/boot.c
> feat(state): jetson booting state

- main_board/src/ui/ambient_light/als.c
for it to go into the message field
> chore(state): reduce message size

- main_board/src/optics/polarizer_wheel/polarizer_wheel.c
increase valid range from 400->500 to 400->550
> fix(polarizer): close notches steps count

- main_board/src/main.c
- main_board/src/ui/sound/sound.c
- main_board/src/ui/sound/sound.h
digital volume set to -10db, main board 4.6 only
> feat(amp): decrease digital volume on dvt2

- lib/dfu/dfu.c
> fix(dfu): release semaphore

- main_board/src/optics/polarizer_wheel/polarizer_wheel.c
as per @ChenLiangChi advice, tested on 3 different units
> fix(polarizer): extend close bumps steps

- west.yml
report hardware states from security mcu
> feat(hw-states): hardware states for sec mcu

- boards/tfh/diamond_main/diamond_main.dts
- main_board/CMakeLists.txt
- main_board/src/main.c
- main_board/src/ui/nfc/nfc.c
- main_board/src/ui/nfc/nfc.h
check that nfc chip is alive with an i2c scan
fixes ORBS-1059
> feat(nfc): read identity register

- main_board/src/power/battery/battery_amber.c
cursor/gpt5 found all these bugs & inconsistencies
> refactor(battery): integrate fixes from ai
